curl/lib: update CFLAGS to fix build break since upmerge
In file included from ./pingpong.c:36:0:
./vtls/vtls.h:24:10: fatal error: curl_setup.h: No such file or directory
 #include "curl_setup.h"
          ^~~~~~~~~~~~~~

Signed-off-by: liuhaitao <liuhaitao@xiaomi.com>